services:
- type: web
  name: react-app
  plan: free
  env: node
  region: california
  buildCommand:
    npm install
    npx prisma generate
  startCommand: npm start
  autoDeploy: true
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: SUPABASE_SERVICE_ROLE_KEY
    sync: false
  - key: VITE_SUPABASE_ANON_KEY
    sync: false
