services:
- type: web
  name: react-app
  plan: free
  env: node
  region: oregon
  buildCommand:
    npm install
    npx prisma generate
  preDeploycommand:
    npx prisma migrate deploy
  startCommand: node index.js
  autoDeploy: true
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: SUPABASE_SERVICE_ROLE_KEY
    sync: false
